 CREATE USER Entities IDENTIFIED BY oracle 
  DEFAULT TABLESPACE users QUOTA 10M ON users TEMPORARY TABLESPACE temp PROFILE DEFAULT;
  GRANT
  CREATE SESSION,CONNECT TO Entities;
  GRANT
  CREATE TABLE TO Entities;
  GRANT
  CREATE VIEW TO Entities;
  GRANT
  CREATE SEQUENCE TO Entities;
  CONNECT Entities/oracle
  SELECT * FROM dual;